@tool
extends RefCounted

const DOMAIN := &"addons/godetx"
const LOCALE_EN := "en"
const LOCALE_ZH_CN := "zh_CN"

const ZH_CN := {
	"Starting runtime": "正在启动运行时",
	"Authorizing runtime": "正在验证运行时",
	"Runtime connection failed": "运行时连接失败",
	"GodotX Runtime did not connect. Check the Godot Output panel, then reload the plugin.": "GodotX 运行时未能连接。请检查 Godot 输出面板，然后重新加载插件。",
	"Authentication failed": "身份验证失败",
	"Provider authentication failed (HTTP %d). Open Connection settings and check the API key or account permissions.": "提供商身份验证失败（HTTP %d）。请打开连接设置并检查 API 密钥或账户权限。",
	"Provider authentication failed. Open Connection settings and check the API key or account permissions.": "提供商身份验证失败。请打开连接设置并检查 API 密钥或账户权限。",
	"Insufficient balance": "余额不足",
	"Provider balance is insufficient. Add credits in the provider billing settings, then retry.": "提供商账户余额不足。请在提供商账单设置中充值后重试。",
	"Stopped": "已停止",
	"Disconnected": "已断开",
	"Connection lost. The next message will start a new session.": "连接已中断。下一条消息将启动新会话。",
	"Connection lost. Reconnecting to the saved conversation.": "连接已中断，正在重新连接已保存的对话。",
	"Clear conversation": "清空对话",
	"Conversations": "对话",
	"New conversation": "新建对话",
	"Conversation actions": "对话操作",
	"Rename conversation": "重命名对话",
	"Delete conversation": "删除对话",
	"Rename": "重命名",
	"Delete this conversation and its saved history? This cannot be undone.": "删除此对话及其已保存的历史记录？此操作无法撤销。",
	"Refresh models": "刷新模型",
	"Connection settings": "连接设置",
	"Ask GodotX to inspect or change this project": "请 GodotX 检查或修改此项目",
	"Add visual attachment": "添加视觉附件",
	"Add image from file": "从文件添加图片",
	"Add project resource preview": "添加项目资源预览",
	"Capture 2D editor viewport": "截取 2D 编辑器视口",
	"Capture 3D editor viewport": "截取 3D 编辑器视口",
	"Add images": "添加图片",
	"Image files": "图片文件",
	"Project images": "项目图片",
	"Drop project resources here": "将项目资源拖放到这里",
	"Previewable resources": "可预览资源",
	"Pasted image": "粘贴的图片",
	"Remove attachment": "移除附件",
	"Annotate image": "批注图片",
	"Image annotations": "图片批注",
	"Arrow": "箭头",
	"Rectangle": "矩形",
	"Circle": "圆圈",
	"Undo annotation": "撤销批注",
	"Clear annotations": "清除批注",
	"Save annotation": "保存批注",
	"Cancel": "取消",
	"Click and drag on the image to mark the target area.": "在图片上点击并拖动以标记目标区域。",
	"Attachment is no longer pending.": "附件已不在待发送列表中。",
	"Annotation could not be saved": "无法保存批注",
	"Annotated image": "已批注图片",
	"Model": "模型",
	"Reasoning effort": "推理强度",
	"Ask for approval": "请求批准",
	"Approve for me": "替我审批",
	"Ask before applying edits, running commands, or starting the game.": "修改项目、运行命令或启动游戏前请求批准。",
	"Automatically approve edits, commands, and game starts.": "自动批准修改、命令和游戏启动。",
	"Edits, commands, and game starts require your approval.": "修改、命令和游戏启动需要你的批准。",
	"Edits, commands, and game starts are approved automatically.": "修改、命令和游戏启动将自动批准。",
	"Stop current task": "停止当前任务",
	"Send message (Enter)": "发送消息（Enter）",
	"GodotX settings": "GodotX 设置",
	"Apply": "应用",
	"Provider": "提供商",
	"Base URL": "基础 URL",
	"API key": "API 密钥",
	"Enter API key": "输入 API 密钥",
	"Allow insecure HTTP": "允许不安全的 HTTP",
	"Disabled (recommended)": "关闭（推荐）",
	"Enabled (unsafe)": "开启（不安全）",
	"Anthropic API root. A bare host automatically uses /v1.": "Anthropic API 根地址；仅填写主机时会自动使用 /v1。",
	"Use only for a trusted test endpoint. The API key is sent without encryption.": "仅用于可信测试端点；API 密钥将以未加密方式发送。",
	"Storage": "存储",
	"Remember secrets": "记住密钥",
	"Store provider secrets as plaintext in Godot's user-level EditorSettings, scoped to this project path. Disable and Apply to remove them.": "将提供商密钥以明文保存到 Godot 用户级 EditorSettings，并限定到当前项目路径。关闭后点击应用即可删除。",
	"Approvals": "审批",
	"Auto-approve all actions": "自动批准所有操作",
	"Automatically approve all allowed edits, commands, and game starts.": "自动批准所有允许的修改、命令和游戏启动。",
	"Game testing": "游戏测试",
	"Use runtime automation": "使用运行时自动化",
	"Run bounded simulated input and assertions inside GodotX-started games without modifying project scripts.": "在 GodotX 启动的游戏内执行有界的模拟输入和断言，无需修改项目脚本。",
	"GodotX approval": "GodotX 审批",
	"Approve": "批准",
	"Decline": "拒绝",
	"You": "你",
	"Thinking": "思考",
	"Show or hide thinking summary": "显示或隐藏思考摘要",
	"Show tool details": "显示工具详情",
	"Hide tool details": "隐藏工具详情",
	"Running": "执行中",
	"Arguments": "参数",
	"Output": "输出",
	"Referenced project context": "已引用项目上下文",
	"Context sources: %d": "上下文来源：%d 个",
	"Context characters: %d": "上下文字符：%d",
	"Index revision: %s": "索引版本：%s",
	"Retrieval was truncated to the safe context budget.": "检索结果已按安全上下文预算截断。",
	"Matched by: %s": "匹配依据：%s",
	"Symbols:": "符号：",
	"Project sources": "项目来源",
	"Open project source": "打开项目来源",
	"Project source is no longer available: %s": "项目来源已不存在：%s",
	"Changes": "更改",
	"Diff": "差异",
	"Failed": "失败",
	"Done": "完成",
	"Queued": "已排队",
	"Passed": "通过",
	"Cancelled": "已取消",
	"Tool failed": "工具执行失败",
	"Writing": "撰写",
	"Working": "执行",
	"Stopping": "正在停止",
	"Waiting for approval": "等待批准",
	"Inspecting editor": "检查编辑器",
	"Worked": "已完成",
	"Worked for %ds": "工作了 %d 秒",
	"%s after %ds": "%s（%d 秒）",
	"%d tokens": "%d Token",
	"Input %d / Output %d tokens": "输入 %d / 输出 %d Token",
	"Context %s": "上下文 %s",
	"Context %d / History %d characters": "上下文 %d / 历史记录 %d 字符",
	"Dropped %d messages / compacted %d tool results": "已省略 %d 条消息 / 已压缩 %d 条工具结果",
	"Earlier": "更早",
	"Newer": "更新",
	"History page %d of %d": "历史记录第 %d/%d 页",
	"Saved conversation %s could not be loaded: %s": "无法加载已保存对话 %s：%s",
	"%d additional saved conversations could not be loaded.": "另有 %d 个已保存对话无法加载。",
	"Snapshot is too large": "快照文件过大",
	"Snapshot is unreadable": "快照文件无法读取",
	"Interrupted-turn recovery could not be saved": "无法保存中断回合的恢复结果",
	"Snapshot is corrupt": "快照文件已损坏",
	"The current request is too long for a safe model context. Shorten it or split it into smaller tasks.": "当前请求过长，无法安全放入模型上下文。请缩短内容或拆分为多个任务。",
	"The task stopped because the same tool calls returned unchanged results repeatedly. Change the instruction or project state before continuing.": "相同工具调用连续返回了未变化的结果，任务已停止。请先调整指令或项目状态再继续。",
	"The task stopped after several attempts produced no new successful result. Change the instruction or project state before continuing.": "任务连续多次尝试仍未产生新的成功结果，已自动停止。请先调整指令或项目状态再继续。",
	"The task reached an internal runaway safety circuit. Review its progress before continuing.": "任务触发了内部失控保护。请检查当前进度后再继续。",
	"The connected client configured a fixed model-step limit and the task reached it.": "当前连接的客户端配置了固定模型步骤上限，任务已达到该上限。",
	"Compacted": "已压缩",
	"Syncing providers": "正在同步提供商",
	"Open settings": "打开设置",
	"Waiting for providers": "等待提供商",
	"Waiting for runtime": "等待运行时",
	"Syncing models": "正在同步模型",
	"Loading conversations": "正在加载对话",
	"Ready": "就绪",
	"%d models available": "可用模型：%d 个",
	"Model refresh failed": "模型刷新失败",
	"Model sync failed": "模型同步失败",
	"Reasoning effort is not available for this model": "此模型不支持推理强度设置",
	"The selected model does not support image input.": "所选模型不支持图片输入。",
	"A message can include at most %d images.": "每条消息最多可包含 %d 张图片。",
	"Visual attachment could not be added": "无法添加视觉附件",
	"Image path is required": "必须提供图片路径",
	"Image file could not be opened": "无法打开图片文件",
	"Image file is empty": "图片文件为空",
	"Image file exceeds the 20 MiB limit": "图片文件超过 20 MiB 限制",
	"Image file could not be decoded": "无法解码图片文件",
	"Texture is unavailable": "纹理不可用",
	"Texture pixels are unavailable": "无法读取纹理像素",
	"Image is empty": "图片为空",
	"Image dimensions exceed the 16 megapixel safety limit": "图片尺寸超过 1600 万像素安全限制",
	"Image could not be copied": "无法复制图片",
	"Image compression format could not be decoded": "无法解码图片压缩格式",
	"Image could not be encoded as PNG": "无法将图片编码为 PNG",
	"Encoded image exceeds the 8 MiB limit": "编码后的图片超过 8 MiB 限制",
	"Image hash could not be calculated": "无法计算图片哈希",
	"Attachment storage directory could not be created": "无法创建附件存储目录",
	"Attachment file could not be created": "无法创建附件文件",
	"Attachment file could not be finalized": "无法完成附件文件写入",
	"Editor visual capture is unavailable": "编辑器视觉捕获不可用",
	"Project resource path is required": "必须提供项目资源路径",
	"Project resource path is invalid": "项目资源路径无效",
	"Project resource path contains an invalid segment": "项目资源路径包含无效片段",
	"Too many project previews are pending": "等待中的项目资源预览过多",
	"The editor resource previewer is unavailable": "编辑器资源预览器不可用",
	"Project resource does not exist: %s": "项目资源不存在：%s",
	"Project resource could not be loaded: %s": "无法加载项目资源：%s",
	"The editor could not generate a preview for %s": "编辑器无法为 %s 生成预览",
	"Editor viewport kind must be 2d or 3d": "编辑器视口类型必须为 2d 或 3d",
	"3D editor viewport index must be between 0 and 3": "3D 编辑器视口索引必须在 0 到 3 之间",
	"Switch to the 2D editor before capturing its viewport": "请先切换到 2D 编辑器，再截取视口",
	"Switch to the 3D editor before capturing its viewport": "请先切换到 3D 编辑器，再截取视口",
	"Editor viewport is unavailable or has no visible size": "编辑器视口不可用或没有可见尺寸",
	"Editor viewport closed before capture completed": "捕获完成前编辑器视口已关闭",
	"Editor viewport texture is unavailable": "编辑器视口纹理不可用",
	"Editor viewport returned an empty image": "编辑器视口返回了空图片",
	"Run npm.cmd run build": "请运行 npm.cmd run build",
	"Runtime package is missing": "缺少 Runtime 运行包",
	"Could not start Node runtime": "无法启动 Node 运行时",
	"Runtime is not connected.": "运行时尚未连接。",
	"Sync the model list before sending a message.": "发送消息前请先同步模型列表。",
	"Save open scripts before sending a task. The task was not sent.": "请先保存已打开的脚本，再发送任务。任务未发送。",
	"Wait for saved conversations to finish loading.": "请等待已保存的对话加载完成。",
	"Wait for the current task before changing connection settings.": "请等待当前任务结束后再更改连接设置。",
	"Invalid runtime message": "运行时消息无效",
	"Unknown error": "未知错误",
	"%s: %s": "%s：%s",
	"Provider discovery failed; using the built-in OpenAI-compatible provider.": "提供商发现失败，改用内置的 OpenAI 兼容提供商。",
	"The runtime returned no usable providers; using OpenAI compatible.": "运行时未返回可用提供商，改用 OpenAI 兼容提供商。",
	"Runtime returned an untracked configure response.": "运行时返回了无法追踪的配置响应。",
	"Connection settings changed before configuration completed.": "配置完成前连接设置已发生变化。",
	"Runtime returned an unexpected configure response.": "运行时返回了意外的配置响应。",
	"The provider returned no usable models.": "提供商未返回可用模型。",
	"Runtime did not create a valid session.": "运行时未创建有效会话。",
	"Runtime returned an invalid conversation snapshot.": "运行时返回了无效的对话快照。",
	"Port collision": "端口冲突",
	"Refused a runtime belonging to another project.": "已拒绝属于其他项目的运行时。",
	"Provider fell back to %s.": "提供商已回退到 %s。",
	"Turn failed": "任务失败",
	"Completed": "已完成",
	"Interrupted": "已中断",
	"Runtime sent an editor tool request without a request ID.": "运行时发送的编辑器工具请求缺少请求 ID。",
	"Could not advance scene context": "无法推进场景上下文",
	"Runtime sent an invalid approval request.": "运行时发送了无效的审批请求。",
	"Runtime sent an invalid live scene approval request. The change was declined.": "运行时发送了无效的实时场景审批请求，修改已拒绝。",
	"Save open scripts before approving this change. The pending change was declined.": "请先保存已打开的脚本，再批准此修改。待处理修改已拒绝。",
	"GodotX plugin files changed. Reload the plugin before sending another task.": "GodotX 插件文件已更改。请重新加载插件后再发送任务。",
	"Approval required": "需要批准",
	"Start the game in the Godot editor": "在 Godot 编辑器中启动游戏",
	"Starting the game saves open editor files, runs project code in the existing Godot editor, and shares bounded debug output with the configured model.": "启动游戏会保存编辑器中已打开的文件、在当前 Godot 编辑器中运行项目代码，并将有界调试输出发送给已配置的模型。",
	"User declined starting the game in the Godot editor": "用户拒绝在 Godot 编辑器中启动游戏",
	"GodotX game debugging is unavailable in this editor": "当前编辑器无法使用 GodotX 游戏调试",
	"A game is already running; GodotX will not replace or adopt it": "已有游戏正在运行；GodotX 不会替换或接管它",
	"There is no current edited scene to run": "当前没有可运行的已编辑场景",
	"mode must be main, current, or scene": "模式必须是 main、current 或 scene",
	"The configured main scene UID is invalid": "配置的主场景 UID 无效",
	"The project does not have a configured main scene": "项目尚未配置主场景",
	"Game scene path must reference a .tscn or .scn resource": "游戏场景路径必须指向 .tscn 或 .scn 资源",
	"The Godot editor did not start the requested game scene": "Godot 编辑器未能启动请求的游戏场景",
	"run_id is required to stop a GodotX game": "停止 GodotX 游戏必须提供 run_id",
	"The GodotX runtime probe is unavailable": "GodotX 运行时探针不可用",
	"A GodotX game run is already active or launching": "已有 GodotX 游戏正在运行或启动中",
	"A game is already running; GodotX will not take ownership of it": "已有游戏正在运行；GodotX 不会接管它",
	"A stable scene path is required for this launch mode": "此启动模式需要稳定的场景路径",
	"scene_path must resolve inside the current project": "scene_path 必须位于当前项目中",
	"The requested GodotX launch is no longer armed": "请求的 GodotX 启动已不再处于待启动状态",
	"run_id does not match the active GodotX run": "run_id 与当前 GodotX 运行不匹配",
	"GodotX does not own the currently running game": "当前运行的游戏不归 GodotX 所有",
	"GodotX cannot prove ownership of the active debugger session": "GodotX 无法确认当前调试会话的所有权",
	"The owned GodotX game is no longer running": "GodotX 所有的游戏已停止运行",
	"Modify the live Godot scene": "修改实时 Godot 场景",
	"Modify Godot scene": "修改 Godot 场景",
	"Modify project files": "修改项目文件",
	"Run project command": "运行项目命令",
	"Command: %s\nWorking directory: %s": "命令：%s\n工作目录：%s",
	"OpenAI compatible": "OpenAI 兼容",
	"API mode": "API 模式",
	"Auto": "自动",
	"Responses": "Responses",
	"Chat Completions": "Chat Completions",
	"%s is required.": "必须填写%s。",
	"%s must start with https:// or http://.": "%s必须以 https:// 或 http:// 开头。",
	"%s must not contain embedded credentials.": "%s不能包含嵌入式凭据。",
	"%s must not contain a query or fragment.": "%s不能包含查询参数或片段。",
	"Remote URLs must use HTTPS. HTTP is allowed only for loopback addresses.": "远程 URL 必须使用 HTTPS；只有回环地址可以使用 HTTP。",
	"List %s files": "列出 %s 文件",
	"List project files": "列出项目文件",
	"Read %s": "读取 %s",
	"Search for %s": "搜索 %s",
	"Search web for %s": "搜索网页：%s",
	"Open webpage %s": "打开网页：%s",
	"Edit %s": "修改 %s",
	"Edit %d files": "修改 %d 个文件",
	"Edit project files": "修改项目文件",
	"Edit leased scene": "修改已锁定场景",
	"Inspect leased scene tree": "检查已锁定场景树",
	"Inspect editor selection": "检查编辑器选中项",
	"Inspect properties %s": "检查属性 %s",
	"Inspect resource %s": "检查资源 %s",
	"Debug current scene": "调试当前场景",
	"Debug %s": "调试 %s",
	"Debug main scene": "调试主场景",
	"Inspect game debug session": "检查游戏调试会话",
	"Capture running game frame": "截取运行中的游戏画面",
	"Stop editor game": "停止编辑器内游戏",
	"Run game automation": "执行游戏自动化",
	"Inspect game automation": "检查游戏自动化",
	"Cancel game automation": "取消游戏自动化",
	"Test main scene": "测试项目主场景",
	"Test current scene": "测试当前场景",
	"Test %s": "测试 %s",
	"Run %s": "运行 %s",
	"Run command": "运行命令",
	"Path: %s": "路径：%s",
	"File suffix: %s": "文件后缀：%s",
	"All project files": "所有项目文件",
	"Limit: %s": "上限：%s",
	"Query: %s": "查询：%s",
	"Results limit: %s": "结果上限：%s",
	"URL: %s": "网址：%s",
	"Content limit: %s characters": "正文上限：%s 字符",
	"Web content was truncated.": "网页正文已截断。",
	"Search provider: %s": "搜索来源：%s",
	"Update": "更新",
	"Create": "创建",
	"Delete": "删除",
	"Scene: %s": "场景：%s",
	"Live scene: %s": "实时场景：%s",
	"Revision: %s": "版本：%s",
	"Add %s  %s": "添加 %s  %s",
	"  Set %s.%s = %s": "  设置 %s.%s = %s",
	"Set %s.%s = %s": "设置 %s.%s = %s",
	"Rename %s -> %s": "重命名 %s -> %s",
	"Remove %s": "删除 %s",
	"Duplicate %s -> %s": "复制 %s -> %s",
	"Duplicate %s under %s (auto name)": "将 %s 复制到 %s 下（自动命名）",
	"Duplicate %s (same parent, auto name)": "复制 %s（同一父节点，自动命名）",
	"Move %s -> %s": "移动 %s -> %s",
	"  Child index: %s": "  子节点索引：%s",
	"  Preserve global transform: %s": "  保留全局变换：%s",
	" (scene root name)": "（使用场景根节点名称）",
	"Instantiate %s -> %s": "实例化 %s -> %s",
	"  Set %s = %s": "  设置 %s = %s",
	"Root: %s": "根节点：%s",
	"Max depth: %s": "最大深度：%s",
	"Max nodes: %s": "最大节点数：%s",
	"Include internal nodes: true": "包含内部节点：是",
	"Node: %s": "节点：%s",
	"Properties: %s": "属性：%s",
	"Resource: %s": "资源：%s",
	"Dependencies: %s": "依赖项：%s",
	"Mode: %s": "模式：%s",
	"Main project scene": "项目主场景",
	"Current editor scene": "编辑器当前场景",
	"Specified scene": "指定场景",
	"Requires approval before launching.": "启动前需要明确批准。",
	"Game launch will be approved automatically.": "游戏启动将自动获批。",
	"Supplied scene path ignored; using the task's frozen current scene.": "已忽略附带的场景路径；实际使用任务提交时冻结的当前场景。",
	"Recent output limit: %s": "最近输出上限：%s",
	"Maximum image dimension: %s": "图像最大边长：%s",
	"Image detail: %s": "图像细节：%s",
	"Captured frame: %s x %s": "已截取画面：%s x %s",
	"Frame: %s": "帧：%s",
	"Attachment: %s": "附件：%s",
	"After sequence: %s": "读取序号 %s 之后的输出",
	"Only a game started by GodotX can be stopped.": "只能停止由 GodotX 启动的游戏。",
	"Automation ID: %s": "自动化 ID：%s",
	"Steps: %d": "步骤数：%d",
	"Stop on failure: %s": "失败时停止：%s",
	"Cleanup policy: %s": "清理策略：%s",
	"Visual capture: %s": "视觉截图：%s",
	"After automation": "自动化完成后",
	"On failure": "失败时",
	"Always": "总是",
	"On success": "仅成功时",
	"Never": "从不",
	"Yes": "是",
	"No": "否",
	"Ready timeout: %s ms": "等待就绪超时：%s 毫秒",
	"Automation timeout: %s ms": "自动化超时：%s 毫秒",
	"%d. Wait %s frames": "%d. 等待 %s 帧",
	"%d. Click %s (button %s)": "%d. 点击 %s（按钮 %s）",
	"%d. Press action %s for %s frames": "%d. 按下动作 %s，持续 %s 帧",
	"%d. Release action %s": "%d. 释放动作 %s",
	"%d. Assert %s exists = %s (timeout %s frames)": "%d. 断言 %s 存在 = %s（超时 %s 帧）",
	"%d. Assert %s.%s %s %s (timeout %s frames)": "%d. 断言 %s.%s %s %s（超时 %s 帧）",
	"%d. Invalid step: %s": "%d. 无效步骤：%s",
	"%d. Unknown step type: %s": "%d. 未知步骤类型：%s",
	"Command: %s": "命令：%s",
	"Timeout: %s ms": "超时：%s 毫秒",
	"Error: %s": "错误：%s",
	"Exit code: %s": "退出代码：%s",
	"Signal: %s": "信号：%s",
	"Game is running in the editor.": "游戏正在编辑器中运行。",
	"Game launch requested in the editor.": "已在编辑器中请求启动游戏。",
	"Game debug session prepared.": "游戏调试会话已准备。",
	"State: stopping": "状态：正在停止",
	"State: paused at breakpoint": "状态：已在断点暂停",
	"State: running": "状态：运行中",
	"State: launch requested": "状态：已请求启动",
	"State: not running": "状态：未运行",
	"Elapsed: %s": "已运行：%s",
	"Runtime probe: connected": "运行时探针：已连接",
	"Runtime probe: confirmed during run": "运行时探针：运行期间已确认",
	"Runtime probe: game paused before handshake": "运行时探针：游戏在握手前已暂停",
	"Runtime probe: waiting": "运行时探针：等待连接",
	"Runtime probe error: %s": "运行时探针错误：%s",
	"Debugger sessions: %d": "调试器会话：%d 个",
	"%d ms": "%d 毫秒",
	"%dm %ds": "%d 分 %d 秒",
	"%ds": "%d 秒",
	"Dropped output records: %d": "已丢弃 %d 条输出记录",
	"Output history was truncated.": "输出历史已截断。",
	"More output is available after sequence %s.": "序号 %s 之后还有更多输出。",
	"Recent output (%d):": "最近输出（%d 条）：",
	"Stop requested for the GodotX game.": "已请求停止 GodotX 启动的游戏。",
	"No GodotX-owned game is running.": "没有由 GodotX 启动且正在运行的游戏。",
	"Game stop request completed.": "游戏停止请求已完成。",
	"Run ID: %s": "运行 ID：%s",
	"State: %s": "状态：%s",
	"Progress: %d/%d": "进度：%d/%d",
	"Cancellation requested.": "已请求取消。",
	"Duration: %s": "耗时：%s",
	"Step results (%d):": "步骤结果（%d 条）：",
	"Failure: %s": "失败原因：%s",
	"Launch: %s": "启动：%s",
	"Automation: %s": "自动化：%s",
	"Cleanup: %s": "清理：%s",
	"Game stopped after test.": "测试后游戏已停止。",
	"Game remains running after test.": "测试后游戏继续运行。",
	"Total duration: %s": "总耗时：%s",
	"Phase timings: %s": "阶段耗时：%s",
	"Skipped": "已跳过",
	"Stop requested": "已请求停止",
	"Timed out": "已超时",
	"Launch failed": "启动失败",
	"Ready timed out": "等待就绪超时",
	"Automation failed": "自动化失败",
	"Automation timed out": "自动化超时",
	"Cleanup failed": "清理失败",
	"Visual capture failed": "视觉截图失败",
	"Already stopped": "已经停止",
	"Validating": "正在验证",
	"Starting": "正在启动",
	"Waiting for runtime probe": "正在等待运行时探针",
	"Running automation": "正在执行自动化",
	"Cleaning up": "正在清理",
	"Validating game test": "正在验证游戏测试",
	"Capturing game frame": "正在截取游戏画面",
	"Starting game": "正在启动游戏",
	"Running game automation": "正在执行游戏自动化",
	"Cleaning up game test": "正在清理游戏测试",
	"Game test completed": "游戏测试已完成",
	"ready": "就绪",
	"automation": "自动化",
	"cleanup": "清理",
	"Warning: %s": "警告：%s",
	"Recent test output (%d):": "最近测试输出（%d 条）：",
	"%d earlier output records omitted.": "已省略前面的 %d 条输出记录。",
	"%d table rows omitted.": "已省略 %d 行表格内容。",
	"Runtime simulation automation is disabled in GodotX settings": "GodotX 设置中的运行时模拟自动化尚未开启",
	"GodotX runtime automation is unavailable in this editor": "当前编辑器无法使用 GodotX 运行时自动化",
	"run_id is required to run game automation": "执行游戏自动化必须提供 run_id",
	"steps must be an array": "steps 必须是数组",
	"run_id and automation_id are required to inspect game automation": "检查游戏自动化必须提供 run_id 和 automation_id",
	"run_id and automation_id are required to cancel game automation": "取消游戏自动化必须提供 run_id 和 automation_id",
	"Applied %d live scene operations.": "已应用 %d 个实时场景操作。",
	"Undo action: %s": "撤销操作：%s",
	"Detailed change output was truncated.": "详细修改输出已截断。",
	"Applied successfully, but detailed change output exceeded the editor response limit.": "修改已成功应用，但详细输出超过编辑器响应限制。",
	"Modified": "已修改",
	"Created": "已创建",
	"Deleted": "已删除",
	"Modified  %s": "已修改  %s",
	"Created  %s": "已创建  %s",
	"Deleted  %s": "已删除  %s",
	"Created  %s (%s)": "已创建  %s（%s）",
	"Modified  %s -> %s": "已修改  %s -> %s",
	"Modified  %s.%s": "已修改  %s.%s",
	"  %s -> %s": "  %s -> %s",
	"Created  %s (copy of %s)": "已创建  %s（复制自 %s）",
	"Created  %s (instance of %s)": "已创建  %s（实例化自 %s）",
	"Output truncated; showing the last %d characters.\n\n": "输出已截断，仅显示最后 %d 个字符。\n\n",
	"\n\nOutput truncated after %d characters.": "\n\n输出在 %d 个字符后被截断。",
	"Editor tool name is required": "必须提供编辑器工具名称",
	"Editor tool arguments must be an object": "编辑器工具参数必须是对象",
	"Godot editor bridge is unavailable": "Godot 编辑器桥接不可用",
	"Editor tool result exceeded the %d byte limit": "编辑器工具结果超过 %d 字节限制",
	"The editor request is not bound to an active task": "编辑器请求未绑定到活动任务",
	"The editor request is missing its scene lease": "编辑器请求缺少场景租约",
	"The editor request has an invalid scene lease": "编辑器请求包含无效的场景租约",
	"The requested scene was not open when this task was submitted": "提交任务时，请求的场景并未打开",
	"The Runtime scene lease does not match the host task": "运行时场景租约与宿主任务不匹配",
	"Editor tool arguments target a different scene lease": "编辑器工具参数指向了其他场景租约",
	"Editor selection is only available for the task's primary scene": "编辑器选中项仅适用于任务的主场景",
	"The completed editor write has no active task context": "已完成的编辑器写入没有活动任务上下文",
	"The active task scene context is invalid": "活动任务的场景上下文无效",
	"The completed editor write targeted an unbound scene": "已完成的编辑器写入指向未绑定场景",
	"The completed editor write returned a mismatched scene state": "已完成的编辑器写入返回了不匹配的场景状态",
	"The completed editor write returned an invalid revision": "已完成的编辑器写入返回了无效版本",
	"The live scene approval is not bound to an active task": "实时场景审批未绑定到活动任务",
	"The live scene approval has an invalid target": "实时场景审批目标无效",
	"The live scene approval targets a scene outside this task": "实时场景审批指向任务范围外的场景",
	"The live scene approval uses a stale scene revision": "实时场景审批使用了过期的场景版本",
	"The live scene approval uses a mismatched scene path": "实时场景审批使用了不匹配的场景路径",
	"The target scene changed.": "目标场景已发生变化。",
	"Live scene write is missing its approved operation ID": "实时场景写入缺少已批准的操作 ID",
	"Live scene write was not approved by the Godot editor": "实时场景写入未获得 Godot 编辑器批准",
	"Live scene write approval is invalid": "实时场景写入审批无效",
	"Live scene write does not match the approved preview": "实时场景写入与已批准的预览不一致",
	"%s. No editor scene operation was executed.": "%s。未执行任何编辑器场景操作。",
	"Generated image preview": "生成图片预览",
	"Show generated image in FileSystem": "在文件系统中显示生成图片",
	"Waiting for Godot to import the generated image": "正在等待 Godot 导入生成图片",
	"Godot is still importing the generated image": "Godot 仍在导入生成图片",
	"Prompt": "提示词",
	"Describe the image to generate": "描述要生成的图片",
	"Image model": "图片模型",
	"Generation settings": "生成设置",
	"Task": "任务",
	"AI UI kit": "AI UI 套件",
	"Single image": "单张图片",
	"Sprite reskin": "精灵换皮",
	"Atlas variation": "图集变体",
	"Describe the new sprite skin": "描述新的精灵外观",
	"Describe the new atlas variation": "描述新的图集变体",
	"Source sprite": "源精灵",
	"Source atlas": "源图集",
	"Source image preview": "源图片预览",
	"Drop one project image here": "将一张项目图片拖放到这里",
	"Drop exactly one project image": "请只拖放一张项目图片",
	"Dropped resource is not a Texture2D image": "拖入的资源不是 Texture2D 图片",
	"No source image selected": "尚未选择源图片",
	"Select project image": "选择项目图片",
	"Select source image": "选择源图片",
	"Select source sprite": "选择源精灵",
	"Select source atlas": "选择源图集",
	"Select a project image from res://": "请选择 res:// 中的项目图片",
	"Selected resource is not an image": "所选资源不是图片",
	"Importing source image": "正在导入源图片",
	"Source image could not be imported": "无法导入源图片",
	"Source image preview is unavailable": "源图片预览不可用",
	"Source image dimensions must be between %d and %d pixels": "源图片宽高必须在 %d 到 %d 像素之间",
	"Source image dimensions changed during import": "源图片在导入过程中发生了尺寸变化",
	"Source image ready": "源图片已就绪",
	"Source image is invalid": "源图片无效",
	"Columns": "列数",
	"Rows": "行数",
	"Atlas frame count must not exceed %d": "图集帧数不能超过 %d",
	"Atlas columns and rows must divide the source dimensions evenly": "图集列数和行数必须能整除源图片尺寸",
	"Frame size: %d x %d, %d frames": "帧尺寸：%d x %d，共 %d 帧",
	"Size": "尺寸",
	"Output size": "输出尺寸",
	"Output size: %dx%d": "输出尺寸：%dx%d",
	"Width": "宽度",
	"Height": "高度",
	"Custom": "自定义",
	"Custom output size is invalid": "自定义输出尺寸无效",
	"Quality": "质量",
	"Background": "背景",
	"Format": "格式",
	"Asset count": "资产数量",
	"Scene context": "场景上下文",
	"Use current 2D viewport": "使用当前 2D 视口",
	"Quality check": "质量检查",
	"Review generated kit with the planner model": "使用规划模型复检生成结果",
	"Generate": "生成",
	"Generate UI kit": "生成 UI 套件",
	"Reskin sprite": "生成换皮精灵",
	"Create atlas variation": "生成图集变体",
	"Cancel image generation": "取消图片生成",
	"Image runtime is not ready": "图片运行时尚未就绪",
	"Image runtime is unavailable": "图片运行时不可用",
	"Image generation ID is required": "必须提供图片生成 ID",
	"An image is already being generated": "已有图片正在生成",
	"Another image generation is already active": "已有另一项图片生成正在进行",
	"Connection lost during image generation": "图片生成期间连接已断开",
	"Configure an image provider": "请配置图片提供商",
	"Checking image capabilities": "正在检查图片能力",
	"Provider does not support image generation": "当前提供商不支持图片生成",
	"Provider does not support image editing": "当前提供商不支持图片编辑",
	"Provider has no edit-capable image models": "当前提供商没有可用于图片编辑的模型",
	"Generating image": "正在生成图片",
	"Generating UI kit": "正在生成 UI 套件",
	"Reskinning sprite": "正在生成换皮精灵",
	"Creating atlas variation": "正在生成图集变体",
	"Planner model: %s": "规划模型：%s",
	"Describe the UI kit needed for the current scene": "描述当前场景需要的 UI 套件",
	"Planner model is unavailable": "规划模型不可用",
	"Capturing Godot context": "正在捕获 Godot 上下文",
	"Capturing the current scene and 2D viewport": "正在捕获当前场景和 2D 视口",
	"Planning UI kit": "正在规划 UI 套件",
	"The planner model is analyzing the Godot scene context": "规划模型正在分析 Godot 场景上下文",
	"Generating asset %d/%d: %s": "正在生成资产 %d/%d：%s",
	"Reviewing UI kit": "正在复检 UI 套件",
	"The planner model is visually reviewing the generated assets": "规划模型正在对生成资产进行视觉复检",
	"UI kit generated": "UI 套件生成完成",
	"UI kit generated with review issues": "UI 套件已生成，但复检发现问题",
	"UI kit generated with automatic green-screen cutout": "UI 套件已生成，并已自动完成绿幕抠图",
	"Transparent background created with local green-screen cutout": "透明背景由本地绿幕抠图生成",
	"Runtime returned no UI kit assets": "运行时未返回任何 UI 套件资产",
	"Plan: %s": "计划：%s",
	"Style: %s": "风格：%s",
	"Assets: %s": "资产：%s",
	"Visual review unavailable": "视觉复检不可用",
	"Visual review skipped: %s": "已跳过视觉复检：%s",
	"Visual review failed: %s": "视觉复检失败：%s",
	"Visual review: %d/100 - %s": "视觉复检：%d/100 - %s",
	"UI kit generation was cancelled": "UI 套件生成已取消",
	"Enter an image prompt": "请输入图片提示词",
	"Image prompt is too long": "图片提示词过长",
	"Transparent backgrounds require PNG or WebP output": "透明背景需要使用 PNG 或 WebP 格式",
	"Image generation could not be started": "无法开始图片生成",
	"Image edit mode is invalid": "图片编辑模式无效",
	"Cancelling image generation": "正在取消图片生成",
	"Runtime returned an invalid image path": "运行时返回了无效的图片路径",
	"Image was saved but its preview could not be loaded": "图片已保存，但无法加载预览",
	"Image generated": "图片生成完成",
	"Sprite reskin generated": "精灵换皮图片生成完成",
	"Atlas variation generated": "图集变体生成完成",
	"Image generated and resized to %dx%d": "图片生成完成，已缩放至 %dx%d",
	"Image generated with automatic green-screen cutout": "图片生成完成，并已自动完成绿幕抠图",
	"Transparent (automatic cutout)": "透明（自动抠图）",
	"The configured provider does not support image generation": "已配置的提供商不支持图片生成",
	"Image generation was cancelled": "图片生成已取消",
	"auto": "自动",
	"low": "低",
	"medium": "中",
	"high": "高",
	"opaque": "不透明",
	"transparent": "透明",
	"Refresh skills": "刷新技能",
	"Project semantic index": "项目语义索引",
	"Skills": "技能",
	"%d skills": "%d 个技能",
	"Offline": "离线",
	"Indexing": "索引中",
	"Project index is waiting for the Runtime": "项目索引正在等待运行时",
	"Rebuild project index": "重建项目索引",
	"New skill": "新建技能",
	"Enabled": "已启用",
	"Project": "项目",
	"Personal": "个人",
	"Built-in": "内置",
	"Scope": "作用域",
	"Skill name": "技能名称",
	"Description": "描述",
	"When should this skill be used?": "这个技能应在什么情况下使用？",
	"Triggers": "触发词",
	"One trigger phrase per line": "每行填写一个触发短语",
	"Capability hints": "能力提示",
	"One ToolKernel capability per line": "每行填写一个 ToolKernel 能力",
	"Instructions": "指令",
	"Reusable instructions loaded only when this skill matches": "仅在技能匹配时加载的可复用指令",
	"Save skill": "保存技能",
	"Delete skill": "删除技能",
	"Delete this SkillX skill permanently?": "永久删除这个 SkillX 技能？",
	"Select a skill first": "请先选择一个技能",
	"Waiting for Runtime": "正在等待运行时",
	"Loading skills": "正在加载技能",
	"%d skill diagnostics": "%d 个技能诊断",
	" (disabled)": "（已禁用）",
	"Could not load skill": "无法加载技能",
	"Could not save skill": "无法保存技能",
	"Could not update skill": "无法更新技能",
	"Could not delete skill": "无法删除技能",
	"Could not rebuild project index": "无法重建项目索引",
	"Name, description, and instructions are required": "名称、描述和指令不能为空",
	"Saving skill": "正在保存技能",
	"Deleting skill": "正在删除技能",
	"Rebuilding project index": "正在重建项目索引",
	"Indexing project": "正在索引项目",
	"Project index failed: %s": "项目索引失败：%s",
	"%d files · %d symbols · %d references · %d dependencies": "%d 个文件 · %d 个符号 · %d 个引用 · %d 条依赖",
	" · partial index": " · 部分索引",
	"Search project symbols for %s": "在项目符号中搜索 %s",
	"Find references to %s": "查找 %s 的引用",
	"Inspect dependencies of %s": "检查 %s 的依赖关系",
	"Query Godot API for %s": "查询 %s 的 Godot API",
	"Search Godot API for %s": "在 Godot API 中搜索 %s",
	"Kinds: %s": "类型：%s",
	"Path prefix: %s": "路径前缀：%s",
	"Symbol: %s": "符号：%s",
	"Direction: %s": "方向：%s",
	"Depth: %s": "深度：%s",
	"Action: %s": "操作：%s",
	"Class: %s": "类：%s",
	"Member query: %s": "成员查询：%s",
}


static func resolve_locale(raw_locale: String) -> String:
	var normalized := raw_locale.strip_edges().replace("-", "_").to_lower()
	if normalized.begins_with("zh"):
		return LOCALE_ZH_CN
	return LOCALE_EN


static func automatic_locale(editor_interface: EditorInterface = null) -> String:
	var raw_locale := OS.get_locale_language()
	if raw_locale.is_empty() and editor_interface != null:
		raw_locale = editor_interface.get_editor_language()
	if raw_locale.is_empty() or raw_locale.to_lower() == "auto":
		raw_locale = TranslationServer.get_tool_locale()
	if raw_locale.is_empty():
		raw_locale = OS.get_locale_language()
	return resolve_locale(raw_locale)


static func install(editor_interface: EditorInterface = null) -> TranslationDomain:
	return install_for_locale(automatic_locale(editor_interface))


static func install_for_locale(raw_locale: String) -> TranslationDomain:
	var domain := TranslationServer.get_or_add_domain(DOMAIN)
	domain.clear()
	var translation := Translation.new()
	translation.locale = LOCALE_ZH_CN
	for source_value in ZH_CN:
		var source := str(source_value)
		translation.add_message(StringName(source), StringName(str(ZH_CN[source_value])))
	domain.add_translation(translation)
	domain.set_locale_override(resolve_locale(raw_locale))
	return domain


static func uninstall() -> void:
	if TranslationServer.has_domain(DOMAIN):
		TranslationServer.remove_domain(DOMAIN)


static func translate(message: String) -> String:
	if not TranslationServer.has_domain(DOMAIN):
		return message
	return str(TranslationServer.get_or_add_domain(DOMAIN).translate(StringName(message)))


static func translate_for_locale(message: String, raw_locale: String) -> String:
	if resolve_locale(raw_locale) != LOCALE_ZH_CN:
		return message
	return str(ZH_CN.get(message, message))
